### ISSUE TITLE
Clicking on Kafka Manager brings up a the main window again

### ISSUE THREAD

**Issue by MikeMester** [pndaproject/platform-console-frontend#58]
<img width="1631" alt="screen shot 2018-01-09 at 7 59 48 pm" src="https://user-images.githubusercontent.com/5067775/34752385-b3d4bca0-f577-11e7-8588-2335f12f9f6f.png">

Note the _blank reference.  Also under firefox the on the main page clicking on kafka (I) doesnt list the brokers.

<img width="1217" alt="screen shot 2018-01-09 at 8 02 13 pm" src="https://user-images.githubusercontent.com/5067775/34752446-07bda430-f578-11e7-9cd6-2e2d59de7460.png">

**Comment by trsmith2** [comment]
This happens when the console hasn't loaded completely/properly. Is there a communication problem between the front/back end blocking the socket.io connection?
